Search.setIndex({
  docnames: ["_include", "background", "data-model", "design", "glossary", "index", "requirements/index", "requirements/truffle"],
  envversion: {
    "sphinx.domains.c": 1,
    "sphinx.domains.changeset": 1,
    "sphinx.domains.cpp": 1,
    "sphinx.domains.javascript": 1,
    "sphinx.domains.math": 2,
    "sphinx.domains.python": 1,
    "sphinx.domains.rst": 1,
    "sphinx.domains.std": 1,
    sphinx: 55
  },
  filenames: ["_include.rst", "background.rst", "data-model.rst", "design.rst", "glossary.rst", "index.rst", "requirements/index.rst", "requirements/truffle.rst"],
  objects: {},
  objnames: {},
  objtypes: {},
  terms: {
    abstract: [1, 3, 4],
    byte: 4,
    case: [5, 7],
    class: 7,
    default: 4,
    import: 7,
    new: [5, 6],
    public: [2, 4, 7],
    while: 3,
    Being: 7,
    For: [1, 7],
    Not: 6,
    That: 3,
    The: [1, 4, 5, 6, 7],
    These: [2, 6, 7],
    Use: 5,
    abi: [4, 7],
    abl: [4, 7],
    about: [1, 5, 7],
    access: [5, 7],
    accommod: 7,
    account: [4, 7],
    achiev: 6,
    across: [2, 7],
    adapt: 3,
    add: 2,
    added: 2,
    adding: 3,
    addit: 3,
    addition: 7,
    address: [4, 6],
    afford: 3,
    after: 7,
    aggreg: 2,
    agnost: 3,
    aid: 5,
    all: [1, 4, 6],
    allow: [1, 7],
    almost: 7,
    alreadi: 7,
    also: [3, 6, 7],
    analog: 7,
    ani: [2, 4, 5, 6, 7],
    annot: 1,
    anoth: [2, 6],
    appli: 6,
    applic: [6, 7],
    appropri: [6, 7],
    arbitrarili: 7,
    architectur: 5,
    artifact: [2, 4, 5, 6],
    artifactor: 3,
    ast: 4,
    attribut: 2,
    auditor: [6, 7],
    autom: 6,
    automat: 1,
    avail: 1,
    background: 5,
    backward: 5,
    balanc: 4,
    base: [6, 7],
    becaus: 7,
    been: [2, 7],
    befor: 7,
    begin: 7,
    behav: 7,
    behavior: [3, 4, 6, 7],
    besid: 7,
    best: 7,
    better: 3,
    between: [2, 3, 7],
    beyond: 7,
    block: 2,
    blockchain: [4, 7],
    both: [2, 3, 7],
    build: [1, 4],
    built: 7,
    busi: [6, 7],
    bytecod: [4, 6],
    call: 6,
    can: [2, 3, 6, 7],
    certain: 2,
    chain: 7,
    chang: [2, 6, 7],
    code: [3, 4, 7],
    collect: 4,
    color: 2,
    combin: 5,
    common: 4,
    commonli: 7,
    compat: [4, 5],
    compil: [4, 6],
    complet: 6,
    compon: [1, 2, 3, 5, 7],
    compos: [4, 7],
    compris: 2,
    comput: 7,
    configur: 1,
    conform: 3,
    consid: 2,
    consum: 6,
    contain: [1, 2, 4],
    content: 5,
    context: 1,
    contract: [1, 3, 4, 5, 6],
    contracts_build_directori: [1, 3],
    control: 3,
    convent: 6,
    convert: 3,
    core: [5, 7],
    correspond: [1, 4, 7],
    cover: 6,
    creat: 7,
    current: [1, 2, 3, 7],
    data: [3, 4, 5, 7],
    databas: 7,
    decentr: 6,
    deepli: 4,
    defin: [2, 3],
    delegatecal: 4,
    deploi: [4, 5, 6],
    deploy: [2, 4, 7],
    deprec: 1,
    describ: [2, 4, 7],
    descript: [4, 7],
    design: 5,
    desir: 3,
    determin: 6,
    develop: [2, 4, 6, 7],
    differ: [2, 6, 7],
    direct: 7,
    directli: 6,
    directori: [1, 4],
    discret: [3, 7],
    discuss: 5,
    disk: [1, 4],
    distinct: 7,
    distribut: 7,
    document: [1, 5, 6],
    don: 5,
    drop: 3,
    dure: 7,
    each: [2, 7],
    earli: 7,
    easi: 7,
    effect: 7,
    effort: 3,
    either: [1, 7],
    enabl: [5, 7],
    encapsul: 3,
    encourag: 7,
    end: 7,
    entir: 2,
    entiti: [2, 4],
    environ: 7,
    etc: 7,
    eth: 6,
    ether: 7,
    ethereum: 4,
    everi: 7,
    evm: [4, 7],
    exampl: [2, 4, 7],
    execut: 7,
    exhaust: 6,
    exist: [1, 3, 5, 6],
    expect: 7,
    explicit: 2,
    explicitli: 2,
    expos: 7,
    express: 7,
    extend: 6,
    extens: 6,
    extern: [3, 4, 7],
    extra: 7,
    facilit: 7,
    file: [1, 3, 4, 5, 6],
    filenam: 1,
    fill: [4, 7],
    find: 7,
    first: [2, 7],
    flavor: 4,
    flexibl: [3, 5],
    follow: [1, 2, 6],
    fork: 2,
    form: [6, 7],
    formal: 1,
    format: [3, 6],
    fresh: 7,
    friendli: 2,
    from: [1, 7],
    front: 7,
    frontend: 6,
    full: [2, 7],
    fund: 7,
    futur: 2,
    ganach: 4,
    gas: 7,
    gener: [2, 3, 6, 7],
    given: [2, 6],
    glanc: 7,
    global: 7,
    glossari: 5,
    goal: 5,
    graphql: 5,
    has: [2, 7],
    have: [2, 6, 7],
    head: 2,
    heavili: 7,
    height: 2,
    help: 6,
    here: 3,
    hexadecim: [4, 7],
    high: [4, 7],
    histor: [2, 6],
    historicblock: 2,
    hook: 3,
    how: [2, 4],
    identifi: [2, 4, 7],
    ignor: 6,
    immut: [2, 4, 7],
    implement: [2, 3],
    impli: 6,
    implicit: [2, 7],
    improv: 5,
    includ: [4, 6, 7],
    incomplet: 2,
    index: [2, 5, 7],
    indic: 6,
    info: 6,
    inform: [5, 6],
    initi: 7,
    instanc: [4, 5, 6],
    instanti: [1, 3],
    instead: [3, 7],
    instruct: 4,
    integr: 7,
    interact: [3, 6],
    interfac: [4, 5, 6],
    intern: 7,
    introduc: 3,
    introduct: 3,
    intuit: 5,
    invok: 6,
    involv: 7,
    iter: [2, 7],
    its: [2, 4, 5, 7],
    itself: 7,
    javascript: 7,
    json: [1, 4, 7],
    just: 7,
    keep: [5, 7],
    kind: 6,
    known: [2, 4, 6],
    languag: [4, 7],
    larger: [2, 7],
    last: 6,
    later: 7,
    latest: 1,
    layer: 3,
    level: [4, 7],
    leverag: 7,
    librari: [4, 6],
    lifecycl: [2, 7],
    like: [2, 7],
    limit: 3,
    link: [2, 4, 6],
    list: [2, 6, 7],
    local: [4, 7],
    longer: 7,
    look: 7,
    lose: 5,
    machin: 7,
    mai: [2, 3, 4, 6, 7],
    mainnet: 4,
    maintain: [3, 5, 7],
    major: [6, 7],
    make: 3,
    manag: 5,
    mani: [2, 6, 7],
    manual: 7,
    map: 4,
    match: 7,
    mean: [2, 7],
    mechan: [3, 4, 7],
    metadata: 6,
    method: 6,
    might: 3,
    migrat: 6,
    mimic: 7,
    minim: 7,
    model: [3, 5],
    modifi: [3, 6],
    modul: 5,
    more: [5, 7],
    most: 7,
    much: 7,
    multipl: 6,
    must: [2, 7],
    name: [1, 4, 5],
    namerecord: 2,
    natur: 7,
    need: 7,
    nest: 4,
    network: [4, 6],
    non: 2,
    note: 5,
    nullabl: 2,
    number: 1,
    object: [1, 3, 4],
    obtain: [3, 7],
    offset: 4,
    often: 7,
    onc: 7,
    one: [2, 6, 7],
    onli: 6,
    oper: [3, 4, 7],
    option: 3,
    order: [2, 6, 7],
    origin: 2,
    other: [4, 6, 7],
    outdat: 7,
    outsid: 7,
    over: [2, 7],
    overview: 5,
    own: [4, 7],
    packag: 1,
    page: 5,
    pai: 7,
    paramount: 7,
    parent: 7,
    part: [1, 7],
    particip: 6,
    particular: [4, 7],
    particularli: 7,
    past: 2,
    payment: 7,
    per: 7,
    perform: [3, 7],
    persist: [3, 5],
    person: 4,
    placehold: 4,
    plain: 3,
    plantuml: 6,
    plu: 2,
    point: 2,
    possibl: [2, 3],
    practic: 7,
    pre: 7,
    prefix: 4,
    present: [2, 5, 7],
    previou: 2,
    previous: 7,
    primari: [5, 6],
    primarili: 6,
    process: [6, 7],
    produc: 6,
    product: 2,
    profil: 6,
    progress: 2,
    prohibit: 3,
    project: [1, 3, 4, 5, 6],
    propos: 6,
    provid: [1, 3, 5, 7],
    purpos: 7,
    queri: [1, 3, 5, 6],
    raw: 7,
    read: [5, 6],
    reason: 7,
    receipt: 7,
    receiv: 7,
    recent: 7,
    recogn: 3,
    recompil: 7,
    record: [5, 7],
    recurs: 7,
    refer: [1, 2, 4, 6],
    referenc: [2, 7],
    reflect: 7,
    relat: [2, 6],
    relationship: 2,
    relev: [1, 5],
    reli: 7,
    reliabl: 7,
    remain: 3,
    render: 6,
    replac: [3, 4],
    repositori: 1,
    repres: [2, 4, 6],
    represent: [4, 7],
    requir: [3, 5, 7],
    reset: [2, 7],
    resolv: 3,
    resourc: 5,
    result: [4, 7],
    retriev: 7,
    rewritten: 2,
    rinkebi: 4,
    robust: 5,
    role: 6,
    run: 6,
    runtim: [4, 7],
    same: [2, 6, 7],
    save: [1, 6],
    schema: [1, 3],
    search: 5,
    secondari: 7,
    section: [2, 4],
    see: 7,
    seek: [2, 3, 5],
    semant: 2,
    send: 6,
    separ: 7,
    serv: [1, 2, 3, 5, 6, 7],
    set: [2, 4, 7],
    sever: 6,
    share: 7,
    should: [6, 7],
    similarli: 7,
    sinc: [2, 3, 6, 7],
    singl: [4, 7],
    singleton: [1, 7],
    smart: [3, 5, 6],
    snapshot: 4,
    softwar: 5,
    sole: 7,
    solid: 7,
    some: 7,
    sourc: [1, 4, 6],
    specif: [1, 4, 5, 6],
    specifi: [1, 2, 6, 7],
    stakehold: [6, 7],
    standalon: 7,
    start: [2, 7],
    state: 7,
    status: 7,
    step: 7,
    still: 7,
    storag: [4, 7],
    store: 1,
    string: [2, 4],
    suit: 7,
    support: [4, 7],
    syntax: 4,
    system: 7,
    target: 2,
    test: 6,
    text: 4,
    than: 2,
    thei: [2, 3, 7],
    them: 7,
    thereof: 5,
    thi: [1, 2, 3, 4, 5, 6, 7],
    thing: 2,
    those: 7,
    throughout: [6, 7],
    time: [2, 7],
    token: 7,
    tool: [3, 6, 7],
    toward: 5,
    track: [2, 7],
    transact: 6,
    transfer: 3,
    translat: [3, 4],
    tree: 4,
    truffl: [2, 3, 4, 6],
    trufflesuit: 1,
    two: 7,
    type: [2, 4, 6],
    uml: 6,
    underli: [2, 7],
    understood: 7,
    unknown: 7,
    unresolv: [4, 7],
    updat: [2, 6],
    use: [2, 3, 4, 6, 7],
    used: [1, 2, 3, 4, 6, 7],
    useful: 7,
    user: [1, 2, 6, 7],
    uses: 6,
    using: 7,
    usual: 4,
    valid: [1, 6, 7],
    valu: [2, 4, 7],
    variabl: 7,
    variou: [2, 7],
    vast: 6,
    version: [1, 2, 4, 7],
    via: [3, 4, 6],
    viabl: 3,
    view: 7,
    vocabulari: 1,
    wai: [3, 6, 7],
    well: 7,
    what: 5,
    when: 7,
    where: [6, 7],
    whether: 7,
    which: [3, 7],
    whose: 2,
    wide: 3,
    within: 1,
    work: 2,
    workflow: 7,
    would: 3,
    write: [1, 5, 7],
    written: [2, 6, 7],
    wrong: 2,
    you: 1
  },
  titles: ["&lt;no title&gt;", "Background", "Data Model", "Software Design", "Glossary", "Truffle DB - Proposal", "Requirements", "1. Saving new artifacts and updating existing"],
  titleterms: {
    case: 6,
    new: 7,
    Use: 6,
    Using: 3,
    address: 7,
    all: 7,
    approach: 3,
    architectur: 1,
    artifact: [1, 3, 7],
    artifactor: 1,
    autom: 7,
    background: 1,
    bytecod: [2, 7],
    call: 7,
    combin: 2,
    compat: 3,
    compil: [2, 7],
    complet: 7,
    config: 1,
    constructor: 2,
    contract: [2, 7],
    data: 2,
    deploi: 7,
    design: 3,
    determin: 7,
    diagram: 6,
    eth: 7,
    exist: 7,
    file: 7,
    given: 7,
    glossari: 4,
    graphql: 3,
    histor: 7,
    ignor: 7,
    indic: 5,
    info: 7,
    inform: 7,
    instanc: [2, 7],
    interact: 7,
    interfac: [2, 3, 7],
    intern: 3,
    invok: 7,
    known: 7,
    last: 7,
    legend: 6,
    librari: 7,
    link: 7,
    metadata: 7,
    method: 7,
    migrat: 7,
    model: 2,
    modifi: 7,
    multipl: 7,
    naiv: 3,
    name: 2,
    network: [2, 7],
    note: 4,
    onli: 7,
    overview: 6,
    primari: 7,
    project: [2, 7],
    propos: 5,
    queri: 7,
    read: 7,
    refer: 7,
    relat: 7,
    requir: 6,
    resolv: 1,
    resourc: 2,
    role: 7,
    run: 7,
    save: 7,
    send: 7,
    smart: 7,
    softwar: 3,
    sourc: [2, 7],
    specif: 7,
    tabl: 5,
    test: 7,
    transact: 7,
    truffl: [1, 5],
    type: 7,
    updat: 7,
    via: 7,
    what: 1
  }
})
